### ISSUE TITLE
TTS keeps stopping 

### ISSUE THREAD

**Issue by jhoc2000** [Danesprite/tts-util-app#4] opened 2020-04-17 04:26 UTC
Whenever I try to open the TTS Util app it keeps stopping.

I'm running version 1.0 on a Xiaomi Pocophone F1 Beryllium with LineageOS 17.1-20200413-NIGHTLY-beryllium ( Android 10) with all expected permissions allowed.

**Comment by Danesprite** [comment] 2020-06-02 09:52
Hello @jhoc2000,

Sorry for my late reply! I'll see if I can reproduce and fix this for you. I plan to release a new version of TTS Util in the next few days.

**Comment by Danesprite** [comment] 2020-06-05 03:47
It looks like this problem occurs if you don't have a text-to-speech engine installed. I can confirm it will be fixed in the next version of TTS Util. If you are using LineageOS without Google's new TTS engine, then you might try [CMU Flite](https://f-droid.org/en/packages/edu.cmu.cs.speech.tts.flite).

**Closed** 2020-06-17 10:26 UTC
